// FETCH ALL CONTRIBUTORS TYPES
export const FETCH_ALL_CONTRIBUTORS_START = 'FETCH_ALL_CONTRIBUTORS_START';
export const FETCH_ALL_CONTRIBUTORS_SUCCESS = 'FETCH_ALL_CONTRIBUTORS_SUCCESS';
export const FETCH_ALL_CONTRIBUTORS_FAILURE = 'FETCH_ALL_CONTRIBUTORS_FAILURE';

// FETCH REPOSITORY TYPES
export const FETCH_REPOSITORY_START = 'FETCH_REPOSITORY_START';
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS';
export const FETCH_REPOSITORY_FAILURE = 'FETCH_REPOSITORY_FAILURE';

// FETCH ALL CONTRIBUTOR USER DETAILS TYPES
export const FETCH_CONTRIBUTORS_USER_DETAILS_START = 'FETCH_CONTRIBUTORS_USER_DETAILS_START';
export const FETCH_CONTRIBUTORS_USER_DETAILS_SUCCESS = 'FETCH_CONTRIBUTORS_USER_DETAILS_SUCCESS';
export const FETCH_CONTRIBUTORS_USER_DETAILS_FAILURE = 'FETCH_CONTRIBUTORS_USER_DETAILS_FAILURE';

// FILTER CONTRIBUTORS TYPES
export const SET_FILTER = 'SET_FILTER';
